delete from `rock_file`;
alter table `rock_file` AUTO_INCREMENT=1;
delete from `rock_assetm`;
alter table `rock_assetm` AUTO_INCREMENT=1;
delete from `rock_assets`;
alter table `rock_assets` AUTO_INCREMENT=1;
delete from `rock_daily`;
alter table `rock_daily` AUTO_INCREMENT=1;
delete from `rock_dailyfx`;
alter table `rock_dailyfx` AUTO_INCREMENT=1;
delete from `rock_docdeil`;
alter table `rock_docdeil` AUTO_INCREMENT=1;
delete from `rock_fininfom`;
alter table `rock_fininfom` AUTO_INCREMENT=1;
delete from `rock_fininfos`;
alter table `rock_fininfos` AUTO_INCREMENT=1;
delete from `rock_flow_bill`;
alter table `rock_flow_bill` AUTO_INCREMENT=1;
delete from `rock_flow_log`;
alter table `rock_flow_log` AUTO_INCREMENT=1;
delete from `rock_flow_rule`;
alter table `rock_flow_rule` AUTO_INCREMENT=1;
delete from `rock_hrpositive`;
alter table `rock_hrpositive` AUTO_INCREMENT=1;
delete from `rock_hrredund`;
alter table `rock_hrredund` AUTO_INCREMENT=1;
delete from `rock_hrtransfer`;
alter table `rock_hrtransfer` AUTO_INCREMENT=1;
delete from `rock_im_group`;
alter table `rock_im_group` AUTO_INCREMENT=1;
delete from `rock_im_groupuser`;
alter table `rock_im_groupuser` AUTO_INCREMENT=1;
delete from `rock_im_mess`;
alter table `rock_im_mess` AUTO_INCREMENT=1;
delete from `rock_im_messzt`;
alter table `rock_im_messzt` AUTO_INCREMENT=1;
delete from `rock_infor`;
alter table `rock_infor` AUTO_INCREMENT=1;
delete from `rock_kq_anay`;
alter table `rock_kq_anay` AUTO_INCREMENT=1;
delete from `rock_kq_dkerr`;
alter table `rock_kq_dkerr` AUTO_INCREMENT=1;
delete from `rock_kq_dkjl`;
alter table `rock_kq_dkjl` AUTO_INCREMENT=1;
delete from `rock_kq_info`;
alter table `rock_kq_info` AUTO_INCREMENT=1;
delete from `rock_kq_out`;
alter table `rock_kq_out` AUTO_INCREMENT=1;
delete from `rock_log`;
alter table `rock_log` AUTO_INCREMENT=1;
delete from `rock_meet`;
alter table `rock_meet` AUTO_INCREMENT=1;
delete from `rock_menucom`;
alter table `rock_menucom` AUTO_INCREMENT=1;
delete from `rock_projectm`;
alter table `rock_projectm` AUTO_INCREMENT=1;
delete from `rock_projects`;
alter table `rock_projects` AUTO_INCREMENT=1;
delete from `rock_reads`;
alter table `rock_reads` AUTO_INCREMENT=1;
delete from `rock_schedule`;
alter table `rock_schedule` AUTO_INCREMENT=1;
delete from `rock_supple`;
alter table `rock_supple` AUTO_INCREMENT=1;
delete from `rock_sjoinv`;
alter table `rock_sjoinv` AUTO_INCREMENT=1;
delete from `rock_supplea`;
alter table `rock_supplea` AUTO_INCREMENT=1;
delete from `rock_todo`;
alter table `rock_todo` AUTO_INCREMENT=1;
delete from `rock_userjl`;
alter table `rock_userjl` AUTO_INCREMENT=1;
delete from `rock_vcard`;
alter table `rock_vcard` AUTO_INCREMENT=1;
delete from `rock_word`;
alter table `rock_word` AUTO_INCREMENT=1;
delete from `rock_work`;
alter table `rock_work` AUTO_INCREMENT=1;
delete from `rock_workbg`;
alter table `rock_workbg` AUTO_INCREMENT=1;
delete from `rock_reward`;
alter table `rock_reward` AUTO_INCREMENT=1;